# Generated by Django 5.2.12 on 2026-04-03 13:17

from django.db import migrations, models


def seed_cases(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    User = apps.get_model("users", "User")

    Case.objects.all().update(status="published")

    company = User.objects.filter(role="company").order_by("id").first()
    if company is None:
        company = User.objects.create(
            username="northstar_logistics",
            full_name="Northstar Logistics",
            role="company",
            about="Логистическая компания, которая тестирует кейсы по аналитике и цифровым продуктам.",
            email="",
            password="",
        )

    demo_cases = [
        {
            "title": "Сократить время обработки заявок на доставку",
            "description": "Нужно предложить процесс и простой прототип дашборда, который поможет операторам быстрее распределять срочные заявки между складами и курьерами в пиковые часы.",
        },
        {
            "title": "Проверить гипотезу по удержанию пользователей финтех-сервиса",
            "description": "Команда запускает новый сценарий онбординга. Требуется собрать план исследования, определить ключевые метрики и описать, как сравнить поведение новых и текущих пользователей.",
        },
        {
            "title": "Подготовить концепт внутренней базы знаний для HR-команды",
            "description": "Компания быстро растет и хочет сократить время адаптации новых сотрудников. Нужен логичный каркас базы знаний, примеры разделов и предложения по поддержанию контента в актуальном состоянии.",
        },
    ]

    for item in demo_cases:
        Case.objects.get_or_create(
            company=company,
            title=item["title"],
            defaults={
                "description": item["description"],
                "status": "published",
            },
        )


def remove_seed_cases(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    titles = [
        "Сократить время обработки заявок на доставку",
        "Проверить гипотезу по удержанию пользователей финтех-сервиса",
        "Подготовить концепт внутренней базы знаний для HR-команды",
    ]
    Case.objects.filter(title__in=titles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('users', '0002_remove_user_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='review_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_review', 'На рассмотрении'), ('published', 'Опубликован')], default='draft', max_length=20),
        ),
        migrations.RunPython(seed_cases, remove_seed_cases),
    ]
